{% set name = "geoid" %}
{% set version = "asp3.5.0" %}
{% set sha256 = "2cffdac6efbfa47a94e8adb650489a267de72770f06656df35f37a531d999f5d" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  fn: geoids.tgz
  url: https://github.com/NeoGeographyToolkit/StereoPipeline/releases/download/geoid1.0/geoids.tgz
  sha256: {{ sha256 }}

build:
  number: 5
  skip: True  # [win]

requirements:
  build:
    - {{ compiler('gfortran') }}  # [linux]

  host:
   # For the Mac it worked only when putting gfortran here, also with version
    - gfortran 14 # [osx]
    - libgfortran 14.2.0
    - llvm-openmp  20.1.3
    - libgfortran5 14.2.0
  run:
 
    - llvm-openmp 20.1.3
    - libgfortran5 14.2.0

test:
  commands:

about:
  home: https://github.com/NeoGeographyToolkit/StereoPipeline
  license: APACHE II
  summary: 'Library to support geoids in the NASA Ames Stereo Pipeline'
  doc_url:
  dev_url:

extra:
  recipe-maintainers:
    - oleg-alexandrov

